### ISSUE TITLE
Crashes when xcrun has non zero exit code

### ISSUE THREAD

**Issue by kabouzeid** [klaaspieter/coc-sourcekit#1]
Overwriting "sourcekit.commandPath" doesn't work if xcrun fails.

```
[coc.nvim] Error on active extension coc-sourcekit: Error: exited with 72
Error: Command failed: xcrun --toolchain swift --find sourcekit-lsp
xcrun: error: sh -c '/Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -sdk /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk -find sourcekit-lsp 2> /dev/null' failed with exit code 17664: (null) (errno=No such file or directory)
xcrun: error: unable to find utility "sourcekit-lsp", not a developer tool or in PATH
xcrun: error: sh -c '/Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -sdk /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk -find sourcekit-lsp 2> /dev/null' failed with exit code 17664: (null) (errno=No such file or directory)
xcrun: error: unable to find utility "sourcekit-lsp", not a developer tool or in PATH
    at /Users/karim/dotfiles/vim/.vim/plugged/coc.nvim/lib/util/index.js:95:24
    at ChildProcess.exithandler (child_process.js:302:5)
    at ChildProcess.emit (events.js:210:5)
    at maybeClose (internal/child_process.js:1023:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:281:5)

```

**Comment by thomfrick** [comment]
Same problem!

**Comment by klaaspieter** [comment]
https://github.com/klaaspieter/coc-sourcekit/pull/2 should fix it. Mind taking a look @thomfrick or @kabouzeid.
